# Generated by Django 6.0.7 on 2026-08-23 18:25

import django.db.models.deletion
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='excelUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=pathlib.PureWindowsPath('C:/Users/user/PycharmProjects/django_pr/edo/uploads/excel'))),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='excelSheets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel.exceluploads')),
            ],
        ),
        migrations.CreateModel(
            name='Consolidatedexcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=pathlib.PureWindowsPath('C:/Users/user/PycharmProjects/django_pr/edo/uploads/excel'))),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('files', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='excel.exceluploads')),
            ],
        ),
    ]
