# Generated by Django 6.0.7 on 2026-08-25 10:27

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolidatedexcel',
            name='file',
            field=models.FileField(upload_to=pathlib.PureWindowsPath('C:/Users/Ruslan/PycharmProjects/edo/edo/edo/uploads/excel')),
        ),
        migrations.AlterField(
            model_name='exceluploads',
            name='file',
            field=models.FileField(upload_to=pathlib.PureWindowsPath('C:/Users/Ruslan/PycharmProjects/edo/edo/edo/uploads/excel')),
        ),
    ]
