# Generated by Django 6.0.7 on 2026-08-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0002_alter_consolidatedexcel_file_alter_exceluploads_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelsheets',
            name='file',
            field=models.FileField(default=False, upload_to=''),
        ),
    ]
