# Generated by Django 6.0.7 on 2026-08-25 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0003_excelsheets_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelsheets',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet', to='excel.exceluploads'),
        ),
    ]
