# Generated by Django 6.0.7 on 2026-08-04 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='name',
        ),
    ]
