# Generated by Django 6.0.7 on 2026-08-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_uploads_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
