# Generated by Django 6.0.7 on 2026-08-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uploads',
            new_name='PdfUploads',
        ),
    ]
